# Generated by Django 3.2.5 on 2021-08-05 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.BooleanField(default=False),
        ),
    ]
