# Generated by Django 3.2.5 on 2021-08-05 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0005_auto_20210805_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
