# Generated by Django 3.2.5 on 2021-08-05 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0006_auto_20210805_1058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='role',
            new_name='seller',
        ),
    ]
