# Generated by Django 3.2.5 on 2021-08-05 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0007_rename_role_profile_seller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='seller',
            new_name='role',
        ),
    ]
