# Generated by Django 3.2.5 on 2021-08-02 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=32, null=True)),
                ('brand', models.CharField(max_length=32, null=True)),
                ('car_model_name', models.CharField(max_length=32, null=True)),
                ('category', models.CharField(choices=[('C', 'Chassis'), ('EX_S', 'Exhaust system'), ('FS', 'Fuel system'), ('T', 'Transmission'), ('LS', 'Lubrication system'), ('CS', 'Cooling system'), ('E', 'Engine'), ('EL_S', 'Electrical system')], max_length=20, null=True)),
                ('description', models.TextField()),
                ('is_new', models.BooleanField(default=False)),
                ('image', models.ImageField(default='default.jpg', upload_to='parts_pics')),
                ('prize', models.IntegerField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
