# Generated by Django 3.2.5 on 2021-08-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('EX_S', 'Exhaust system'), ('E', 'Engine'), ('FS', 'Fuel system'), ('EL_S', 'Electrical system'), ('T', 'Transmission'), ('LS', 'Lubrication system'), ('CS', 'Cooling system'), ('C', 'Chassis')], max_length=20, null=True),
        ),
    ]
