# Generated by Django 3.2.5 on 2021-08-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0002_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('EL_S', 'Electrical system'), ('C', 'Chassis'), ('CS', 'Cooling system'), ('T', 'Transmission'), ('E', 'Engine'), ('EX_S', 'Exhaust system'), ('FS', 'Fuel system'), ('LS', 'Lubrication system')], max_length=20, null=True),
        ),
    ]
