# Generated by Django 3.2.5 on 2021-08-05 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0003_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='role',
            field=models.BooleanField(default=False),
        ),
    ]
