# Generated by Django 3.2.5 on 2021-08-05 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0004_post_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='role',
        ),
    ]
