# Generated by Django 3.2.5 on 2021-08-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0005_remove_post_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='role',
            field=models.BooleanField(default=False),
        ),
    ]
