# Generated by Django 3.2.5 on 2021-08-09 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0007_remove_post_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-prize']},
        ),
    ]
