# Generated by Django 3.2.6 on 2021-08-17 04:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=32, null=True)),
                ('brand', models.CharField(max_length=32, null=True)),
                ('car_model_name', models.CharField(max_length=32, null=True)),
                ('description', models.TextField()),
                ('quality', models.IntegerField(choices=[(0, 'New'), (1, 'Old')], default=0)),
                ('image', models.ImageField(default='default.jpg', upload_to='parts_pics')),
                ('price', models.IntegerField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
            options={
                'ordering': ['-price'],
            },
        ),
    ]
