# Generated by Django 3.2.6 on 2021-08-14 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_carpart_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carpart',
            name='is_new',
        ),
        migrations.AddField(
            model_name='carpart',
            name='quality',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'Old')], default=0),
        ),
    ]
